/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */


var fibroeven = function (input) {
	//initializes variables for fibro adding and sum
	var sum = 0;
	var num1 = 1;
	var num2 = 0;
	var temp = 0;

	//builds fibronacci sequence while adding the even values
	while(num1 < 4000000)
	{
	    var temp = num1;
	    var num1 = num1 + num2;
	    var num2 = temp;
	    
	    if(num1 %2 === 0)
	        sum += num1; 
	}

	return(sum);
}
